### PR TITLE
fix(shared): Turn base `AggregateRootId` into a trait

### LINKED ISSUE #25: Cannot initialize readonly property AggregateRootId:: :$value from scope BookId
Hey,

I followed the instructions in the readme to start the project as I tried the endpoints on the `/api` page I received the following error:

Commit 635d064a5339cfc309b11ad6f1a86b17c7e021d8
Url: `https://localhost/api/books?page=1`

<details>
<summary>JSON Response</summary>
```json
{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Cannot initialize readonly property App\\Shared\\Domain\\ValueObject\\AggregateRootId::$value from scope App\\BookStore\\Domain\\ValueObject\\BookId",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/srv/app/vendor/doctrine/persistence/src/Persistence/Reflection/RuntimePublicReflectionProperty.php",
      "line": 59,
      "args": []
    },
    {
      "namespace": "",
      "short_class": "ReflectionProperty",
      "class": "ReflectionProperty",
      "type": "->",
      "function": "setValue",
      "file": "/srv/app/vendor/doctrine/persistence/src/Persistence/Reflection/RuntimePublicReflectionProperty.php",
      "line": 59,
      "args": [
        [
          "object",
          "App\\BookStore\\Domain\\ValueObject\\BookId"
        ],
        [
          "object",
          "Symfony\\Component\\Uid\\UuidV4"
        ]
      ]
    },
    {
      "namespace": "Doctrine\\Persistence\\Reflection",
      "short_class": "RuntimePublicReflectionProperty",
      "class": "Doctrine\\Persistence\\Reflection\\RuntimePublicReflectionProperty",
      "type": "->",
      "function": "setValue",
      "file": "/srv/app/vendor/doctrine/persistence/src/Persistence/Reflection/TypedNoDefaultReflectionPropertyBase.php",
      "line": 64,
      "args": [
        [
          "object",
          "App\\BookStore\\Domain\\ValueObject\\BookId"
        ],
        [
          "object",
          "Symfony\\Component\\Uid\\UuidV4"
        ]
      ]
    },
    {
      "namespace": "Doctrine\\Persistence\\Reflection",
      "short_class": "TypedNoDefaultRuntimePublicReflectionProperty",
      "class": "Doctrine\\Persistence\\Reflection\\TypedNoDefaultRuntimePublicReflectionProperty",
      "type": "->",
      "function": "setValue",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionReadonlyProperty.php",
      "line": 40,
      "args": [
        [
          "object",
          "App\\BookStore\\Domain\\ValueObject\\BookId"
        ],
        [
          "object",
          "Symfony\\Component\\Uid\\UuidV4"
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM\\Mapping",
      "short_class": "ReflectionReadonlyProperty",
      "class": "Doctrine\\ORM\\Mapping\\ReflectionReadonlyProperty",
      "type": "->",
      "function": "setValue",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionEmbeddedProperty.php",
      "line": 81,
      "args": [
        [
          "object",
          "App\\BookStore\\Domain\\ValueObject\\BookId"
        ],
        [
          "object",
          "Symfony\\Component\\Uid\\UuidV4"
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM\\Mapping",
      "short_class": "ReflectionEmbeddedProperty",
      "class": "Doctrine\\ORM\\Mapping\\ReflectionEmbeddedProperty",
      "type": "->",
      "function": "setValue",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php",
      "line": 2753,
      "args": [
        [
          "object",
          "App\\BookStore\\Domain\\Model\\Book"
        ],
        [
          "object",
          "Symfony\\Component\\Uid\\UuidV4"
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM",
      "short_class": "UnitOfWork",
      "class": "Doctrine\\ORM\\UnitOfWork",
      "type": "->",
      "function": "createEntity",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php",
      "line": 266,
      "args": [
        [
          "string",
          "App\\BookStore\\Domain\\Model\\Book"
        ],
        [
          "array",
          {
            "id.value": [
              "object",
              "Symfony\\Component\\Uid\\UuidV4"
            ],
            "name.value": [
              "string",
              "foo"
            ],
            "description.value": [
              "string",
              "bar"
            ],
            "author.value": [
              "string",
              "jj"
            ],
            "content.value": [
              "string",
              "this is an example"
            ],
            "price.amount": [
              "integer",
              10
            ]
          }
        ],
        [
          "array",
          {
            "doctrine.customTreeWalkers": [
              "array",
              [
                [
                  "string",
                  "Doctrine\\ORM\\Tools\\Pagination\\WhereInWalker"
                ]
              ]
            ],
            "doctrine.id.count": [
              "integer",
              2
            ],
            "deferEagerLoad": [
              "boolean",
              true
            ],
            "fetchAlias": [
              "string",
              "book"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM\\Internal\\Hydration",
      "short_class": "ObjectHydrator",
      "class": "Doctrine\\ORM\\Internal\\Hydration\\ObjectHydrator",
      "type": "->",
      "function": "getEntity",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php",
      "line": 492,
      "args": [
        [
          "array",
          {
            "id.value": [
              "object",
              "Symfony\\Component\\Uid\\UuidV4"
            ],
            "name.value": [
              "string",
              "foo"
            ],
            "description.value": [
              "string",
              "bar"
            ],
            "author.value": [
              "string",
              "jj"
            ],
            "content.value": [
              "string",
              "this is an example"
            ],
            "price.amount": [
              "integer",
              10
            ]
          }
        ],
        [
          "string",
          "book"
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM\\Internal\\Hydration",
      "short_class": "ObjectHydrator",
      "class": "Doctrine\\ORM\\Internal\\Hydration\\ObjectHydrator",
      "type": "->",
      "function": "hydrateRowData",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php",
      "line": 148,
      "args": [
        [
          "array",
          {
            "id_0": [
              "string",
              "6f6413db-3f20-445b-8ef5-30b081fd0f46"
            ],
            "name_1": [
              "string",
              "foo"
            ],
            "description_2": [
              "string",
              "bar"
            ],
            "author_3": [
              "string",
              "jj"
            ],
            "content_4": [
              "string",
              "this is an example"
            ],
            "price_5": [
              "integer",
              10
            ]
          }
        ],
        [
          "array",
          []
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM\\Internal\\Hydration",
      "short_class": "ObjectHydrator",
      "class": "Doctrine\\ORM\\Internal\\Hydration\\ObjectHydrator",
      "type": "->",
      "function": "hydrateAllData",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php",
      "line": 270,
      "args": []
    },
    {
      "namespace": "Doctrine\\ORM\\Internal\\Hydration",
      "short_class": "AbstractHydrator",
      "class": "Doctrine\\ORM\\Internal\\Hydration\\AbstractHydrator",
      "type": "->",
      "function": "hydrateAll",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php",
      "line": 1234,
      "args": [
        [
          "object",
          "Doctrine\\DBAL\\Result"
        ],
        [
          "object",
          "Doctrine\\ORM\\Query\\ResultSetMapping"
        ],
        [
          "array",
          {
            "doctrine.customTreeWalkers": [
              "array",
              [
                [
                  "string",
                  "Doctrine\\ORM\\Tools\\Pagination\\WhereInWalker"
                ]
              ]
            ],
            "doctrine.id.count": [
              "integer",
              2
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM",
      "short_class": "AbstractQuery",
      "class": "Doctrine\\ORM\\AbstractQuery",
      "type": "->",
      "function": "executeIgnoreQueryCache",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php",
      "line": 1175,
      "args": [
        [
          "null",
          null
        ],
        [
          "integer",
          1
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM",
      "short_class": "AbstractQuery",
      "class": "Doctrine\\ORM\\AbstractQuery",
      "type": "->",
      "function": "execute",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php",
      "line": 911,
      "args": [
        [
          "null",
          null
        ],
        [
          "integer",
          1
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM",
      "short_class": "AbstractQuery",
      "class": "Doctrine\\ORM\\AbstractQuery",
      "type": "->",
      "function": "getResult",
      "file": "/srv/app/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php",
      "line": 165,
      "args": [
        [
          "integer",
          1
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM\\Tools\\Pagination",
      "short_class": "Paginator",
      "class": "Doctrine\\ORM\\Tools\\Pagination\\Paginator",
      "type": "->",
      "function": "getIterator",
      "file": "/srv/app/src/Shared/Infrastructure/Doctrine/DoctrinePaginator.php",
      "line": 78,
      "args": []
    },
    {
      "namespace": "App\\Shared\\Infrastructure\\Doctrine",
      "short_class": "DoctrinePaginator",
      "class": "App\\Shared\\Infrastructure\\Doctrine\\DoctrinePaginator",
      "type": "->",
      "function": "getIterator",
      "file": "/srv/app/src/Shared/Infrastructure/Doctrine/DoctrineRepository.php",
      "line": 39,
      "args": []
    },
    {
      "namespace": "App\\Shared\\Infrastructure\\Doctrine",
      "short_class": "DoctrineRepository",
      "class": "App\\Shared\\Infrastructure\\Doctrine\\DoctrineRepository",
      "type": "->",
      "function": "getIterator",
      "file": "/srv/app/src/BookStore/Infrastructure/ApiPlatform/State/Provider/BookCollectionProvider.php",
      "line": 43,
      "args": []
    },
    {
      "namespace": "App\\BookStore\\Infrastructure\\ApiPlatform\\State\\Provider",
      "short_class": "BookCollectionProvider",
      "class": "App\\BookStore\\Infrastructure\\ApiPlatform\\State\\Provider\\BookCollectionProvider",
      "type": "->",
      "function": "provide",
      "file": "/srv/app/vendor/api-platform/core/src/State/CallableProvider.php",
      "line": 43,
      "args": [
        [
          "object",
          "ApiPlatform\\Metadata\\GetCollection"
        ],
        [
          "array",
          []
        ],
        [
          "array",
          {
            "operation": [
              "object",
              "ApiPlatform\\Metadata\\GetCollection"
            ],
            "filters": [
              "array",
              {
                "page": [
                  "string",
                  "1"
                ]
              }
            ],
            "operation_name": [
              "string",
              "_api_/books.{_format}_get_collection"
            ],
            "resource_class": [
              "string",
              "App\\BookStore\\Infrastructure\\ApiPlatform\\Resource\\BookResource"
            ],
            "skip_null_values": [
              "boolean",
              true
            ],
            "iri_only": [
              "boolean",
              false
            ],
            "request_uri": [
              "string",
              "/api/books?page=1"
            ],
            "uri": [
              "string",
              "https://localhost/api/books?page=1"
            ],
            "input": [
              "null",
              null
            ],
            "output": [
              "null",
              null
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\State",
      "short_class": "CallableProvider",
      "class": "ApiPlatform\\State\\CallableProvider",
      "type": "->",
      "function": "provide",
      "file": "/srv/app/vendor/api-platform/core/src/Symfony/EventListener/ReadListener.php",
      "line": 88,
      "args": [
        [
          "object",
          "ApiPlatform\\Metadata\\GetCollection"
        ],
        [
          "array",
          []
        ],
        [
          "array",
          {
            "operation": [
              "object",
              "ApiPlatform\\Metadata\\GetCollection"
            ],
            "filters": [
              "array",
              {
                "page": [
                  "string",
                  "1"
                ]
              }
            ],
            "operation_name": [
              "string",
              "_api_/books.{_format}_get_collection"
            ],
            "resource_class": [
              "string",
              "App\\BookStore\\Infrastructure\\ApiPlatform\\Resource\\BookResource"
            ],
            "skip_null_values": [
              "boolean",
              true
            ],
            "iri_only": [
              "boolean",
              false
            ],
            "request_uri": [
              "string",
              "/api/books?page=1"
            ],
            "uri": [
              "string",
              "https://localhost/api/books?page=1"
            ],
            "input": [
              "null",
              null
            ],
            "output": [
              "null",
              null
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Symfony\\EventListener",
      "short_class": "ReadListener",
      "class": "ApiPlatform\\Symfony\\EventListener\\ReadListener",
      "type": "->",
      "function": "onKernelRequest",
      "file": "/srv/app/vendor/symfony/event-dispatcher/Debug/WrappedListener.php",
      "line": 115,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "WrappedListener",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
      "type": "->",
      "function": "__invoke",
      "file": "/srv/app/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 230,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "callListeners",
      "file": "/srv/app/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 59,
      "args": [
        [
          "array",
          [
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ]
          ]
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/srv/app/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php",
      "line": 153,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ],
        [
          "string",
          "kernel.request"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "TraceableEventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/srv/app/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 129,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ],
        [
          "string",
          "kernel.request"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handleRaw",
      "file": "/srv/app/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 75,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handle",
      "file": "/srv/app/vendor/symfony/http-kernel/Kernel.php",
      "line": 202,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ],
        [
          "boolean",
          true
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "Kernel",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->",
      "function": "handle",
      "file": "/srv/app/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php",
      "line": 35,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Runtime\\Runner\\Symfony",
      "short_class": "HttpKernelRunner",
      "class": "Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner",
      "type": "->",
      "function": "run",
      "file": "/srv/app/vendor/autoload_runtime.php",
      "line": 29,
      "args": []
    },
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "require_once",
      "file": "/srv/app/public/index.php",
      "line": 7,
      "args": [
        [
          "string",
          "/srv/app/vendor/autoload_runtime.php"
        ]
      ]
    }
  ]
}
```
</details>

Not sure how to fix that issue. `readonly` properties are also new to me, especially in inheritance.

### PR DESCRIPTION
**Pull request by chalasr**
My proposal to fix #25. Not sure why this bug isn't caught by `DoctrineBookRepositoryTest` nor how we can make it able to do so. 💡 welcome

### CODE REVIEW

File: tests/BookStore/Integration/Doctrine/DoctrineBookRepositoryTest.php [hunk 1]
```diff
@@ -202,6 +203,8 @@ public function testCount(): void
             $repository->save($book);
         }
 
+        static::getContainer()->get(EntityManagerInterface::class)->clear();
```
Comment (mtarld) [inline tests/BookStore/Integration/Doctrine/DoctrineBookRepositoryTest.php:206]: Maybe it makes more sense to put the clear in `testOfId` instead, WDYT?

Comment (chalasr) [reply tests/BookStore/Integration/Doctrine/DoctrineBookRepositoryTest.php]: Works for me, done!

File: tests/BookStore/Integration/Doctrine/DoctrineBookRepositoryTest.php [hunk 2]
```diff
@@ -75,6 +76,8 @@ public function testOfId(): void
         $book = DummyBookFactory::createBook();
         $repository->save($book);
 
+        static::getContainer()->get(EntityManagerInterface::class)->clear();
+
         static::assertSame($book, $repository->ofId($book->id));
```
Comment (mtarld) [inline tests/BookStore/Integration/Doctrine/DoctrineBookRepositoryTest.php:81]:
```suggestion
        static::assertEquals($book, $repository->ofId($book->id));
```
As they're aren't the same reference anymore

**Review by mtarld — APPROVED** [review]
